plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-4.0.0-rc.34.cjs

packageExtensions:
  'rollup-plugin-workbox@*':
    dependencies:
      'rollup': '3.9.1'

nodeLinker: pnp
