services:
  api:
    build:
      context: ./api

    restart: "no"

    stop_grace_period: 30s

    cpu_shares: 2048
    # mem_limit: 256m

    env_file: .env

    tty: true

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

  crawler:
    build:
      context: ./crawler

    restart: "no"

    stop_grace_period: 30s

    cpu_shares: 2048
    # mem_limit: 256m

    env_file: .env

    tty: true

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

  telegram-notifier:
    build:
      context: ./telegram-notifier

    restart: "no"

    stop_grace_period: 30s

    cpu_shares: 2048
    # mem_limit: 256m

    env_file: .env

    tty: true

    volumes:
      - type: bind
        source: ./db
        target: /db
        bind:
          create_host_path: true

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'
  pwa:
    build:
      context: ./pwa

    restart: "no"

    stop_grace_period: 30s

    cpu_shares: 2048
    # mem_limit: 256m

    env_file: .env

    tmpfs:
      - /var/cache

    tty: true

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'
