networks:
  internal:
  alwatr-private-network:
    name: alwatr-private-network
    external: true
  alwatr-public-network:
    name: alwatr-public-network
    external: true

services:
  nginx:
    build:
      context: ./nginx
      args:
        - NGINX_VERSION=${NGINX_VERSION:-1.24}

    networks:
      - internal
      - alwatr-public-network

    restart: unless-stopped

    depends_on:
      - php

    cpu_shares: 2048
    mem_limit: ${NGINX_MEMORY_LIMIT:-256m}

    volumes:
      - type: bind
        source: ./_data/
        target: /var/www/html/
        read_only: true
        bind:
          create_host_path: true

    tmpfs:
      - /var/cache

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.rule: Host:${DOMAIN}
      traefik.frontend.entryPoints: http, https
      # traefik.frontend.redirect.entryPoint: https

  php:
    build:
      context: ./php
      args:
        - PHP_VERSION=${PHP_VERSION:-8.1}
        - WORDPRESS_VERSION=${WORDPRESS_VERSION:-6}
        - APT_INSTALL=${APT_INSTALL:-}
        - PHP_EXT_INSTALL=${PHP_EXT_INSTALL:-}
        - SOURCEGUARDIAN_LOADER=${SOURCEGUARDIAN_LOADER:-0}
        - IONCUBE_LOADER=${IONCUBE_LOADER:-0}

    networks:
      internal:
        aliases:
          - wordpress-php-fpm
      alwatr-private-network:

    restart: unless-stopped

    cpu_shares: 1024
    mem_limit: ${WP_MAX_MEMORY_LIMIT:-768M}

    volumes:
      - type: bind
        source: ./_data/
        target: /var/www/html/
        bind:
          create_host_path: true

    tmpfs:
      - /var/cache

    env_file: .env

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

    environment:
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_CACHE', true);
        define('WP_POST_REVISIONS', 2);
        define('IMAGE_EDIT_OVERWRITE', true);
        define('FORCE_SSL_LOGIN', false);
        define('FORCE_SSL_ADMIN', false);
        define('WP_MEMORY_LIMIT', '${WP_MEMORY_LIMIT:-256M}');
        define('WP_MAX_MEMORY_LIMIT', '${WP_MAX_MEMORY_LIMIT:-768M}');
        define('DISABLE_WP_CRON', true);
