networks:
  alwatr-private-network:
    name: alwatr-private-network
    external: true
  alwatr-public-network:
    name: alwatr-public-network
    external: true

services:
  nocodb:
    image: ghcr.io/alimd/nocodb:${IMAGE_VERSION:-0.109.1}

    cpu_shares: 1024
    mem_limit: 300m

    stop_grace_period: 5s

    restart: unless-stopped

    networks:
      - alwatr-private-network
      - alwatr-public-network

    env_file: .env

    volumes:
      - type: bind
        source: ./_data
        target: /usr/app/data
        bind:
          create_host_path: true

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

    labels:
      traefik.enable: true
      traefik.port: 8080
      traefik.frontend.rule: Host:${DOMAIN}
      traefik.frontend.entryPoints: http, https
      traefik.frontend.redirect.entryPoint: https
