services:
  dockovpn:
    image: docker.io/v2fly/v2fly-core:latest

    ports:
      - ${PORT}:${PORT}
      - ${PORT}:${PORT}/udp

    cpu_shares: 512
    mem_limit: 256m

    restart: unless-stopped

    command:
      - run
      - -c
      - /etc/config/${CONFIG}.json
      - -format
      - jsonv5

    env_file: .env

    volumes:
      - type: bind
        source: ./secret
        target: /etc/config
        read_only: true
