networks:
  internal:
  alwatr-public-network:
    name: alwatr-public-network
    external: true

services:
  telegram-notifier:
    image: ghcr.io/alimd/telegram-notifier:${TELEGRAM_NOTIFIER_VERSION}

    cpu_shares: 512
    mem_limit: 256m

    restart: unless-stopped

    networks:
      alwatr-public-network:

    environment:
      - STORAGE_PATH=/storage
      - ACCESS_TOKEN=${TELEGRAM_NOTIFIER_TOKEN}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ALWATR_DEBUG=${TELEGRAM_NOTIFIER_DEBUG:-}
      - DEBUG=${TELEGRAM_NOTIFIER_DEBUG:-}

    volumes:
      - type: bind
        source: ./_data/telegram-notifier
        target: /storage
        bind:
          create_host_path: true

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.rule: Host:${TELEGRAM_NOTIFIER_DOMAIN}
      traefik.frontend.entryPoints: http, https
      traefik.frontend.redirect.entryPoint: https
