networks:
  alwatr-private-network:
    name: alwatr-private-network
    external: true
  alwatr-public-network:
    name: alwatr-public-network
    external: true

services:
  php-apache:
    build:
      context: ./php
      args:
        - PHP_VERSION=${PHP_VERSION:-8.1}
        - APT_INSTALL=${APT_INSTALL:-}
        - PHP_EXT_INSTALL=${PHP_EXT_INSTALL:-}
        - APACHE_MODULE=${APACHE_MODULE:-}
        - SOURCEGUARDIAN_LOADER=${SOURCEGUARDIAN_LOADER:-0}
        - IONCUBE_LOADER=${IONCUBE_LOADER:-0}

    networks:
      - alwatr-public-network
      - alwatr-private-network

    restart: unless-stopped

    cpu_shares: 1024
    mem_limit: ${MEMORY_LIMIT:-256m}

    volumes:
      - type: bind
        source: ./_data/
        target: /var/www/html/
        bind:
          create_host_path: true

    tmpfs:
      - /tmp

    env_file: .env

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.rule: Host:${DOMAIN}
      traefik.frontend.entryPoints: http, https
      traefik.frontend.redirect.entryPoint: https
