version: '2'

networks:
  alwatr-private-network:
    external:
      name: alwatr-private-network
  alwatr-public-network:
    external:
      name: alwatr-public-network

services:
  php:
    build:
      context: ./php
      args:
        - PHP_VERSION=${PHP_VERSION}
        - SOURCEGUARDIAN_LOADER=${SOURCEGUARDIAN_LOADER}
        - IONCUBE_LOADER=${IONCUBE_LOADER}

    hostname: php.alwatr.io

    networks:
      - alwatr-public-network
      - alwatr-private-network

    restart: unless-stopped

    cpu_shares: 1024
    mem_limit: ${MEMORY_LIMIT}

    volumes:
      - type: bind
        source: ./_data/
        target: /var/www/html/

    tmpfs:
      - /tmp

    env_file:
      - .env

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.rule: Host:${DOMAIN}
      traefik.frontend.entryPoints: http, https
      traefik.frontend.redirect.entryPoint: https
