networks:
  internal:
  alwatr-public-network:
    name: alwatr-public-network
    external: true

services:

  storage-server:
    image: ghcr.io/alimd/storage-server:${STORAGE_SERVER_VERSION:-next}

    cpu_shares: 1024
    mem_limit: 256m

    stop_grace_period: 30s

    restart: unless-stopped

    networks:
      internal:
        aliases:
          - "${APP_ID}-storage-server"

    environment:
      - STORAGE_PATH=/storage
      - TOKEN=${TOKEN}

    volumes:
      - type: bind
        source: ./_data/storage
        target: /storage
        bind:
          create_host_path: true

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'


  telegram-notifier:
    image: ghcr.io/alimd/telegram-notifier:${TELEGRAM_NOTIFIER_VERSION:-next}

    cpu_shares: 512
    mem_limit: 256m

    restart: unless-stopped

    networks:
      internal:
        aliases:
          - "${APP_ID}-telegram-notifier"

    environment:
      - STORAGE_PATH=/storage
      - TOKEN=${ACCESS_TOKEN}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}

    volumes:
      - type: bind
        source: ./_data/telegram-notifier
        target: /storage
        bind:
          create_host_path: true

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'


  flight-crawler:
    image: ghcr.io/alimd/flight-crawler:${FLIGHT_CRAWLER_VERSION:-next}

    cpu_shares: 512
    mem_limit: 256m

    restart: unless-stopped

    networks:
      internal:

    environment:
      - ?

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'


  api:
    image: ghcr.io/alimd/api:${API_VERSION:-next}

    cpu_shares: 1024
    mem_limit: 256m

    restart: unless-stopped

    networks:
      internal:
      alwatr-public-network:

    environment:
      - STORAGE_HOST=${APP_ID}-storage-server
      - ?

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'


  pwa:
    image: ghcr.io/alimd/api:${PWA_VERSION:-next}

    cpu_shares: 1024
    mem_limit: 256m

    restart: unless-stopped

    networks:
      alwatr-public-network:

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.rule: Host:${DOMAIN}
      traefik.frontend.entryPoints: http, https
      traefik.frontend.redirect.entryPoint: https
