networks:
  alwatr-public-network:
    name: alwatr-public-network
    external: true

services:
  service-proxy:
    image: ${TRAEFIK_IMAGE}

    # hostname: traefik-proxy.alwatr.io

    # networks:
    #   - alwatr-public-network

    restart: unless-stopped

    cpu_shares: 4096
    mem_limit: 256m

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

    ports:
      - 80:80
      - 443:443

    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./traefik.toml
        target: /traefik.toml
      - type: bind
        source: ./_data/acme.json
        target: /acme.json

    # labels:
    # traefik.enable: true
    # traefik.port: 8080
    # traefik.http.routers.router0.rule: Host(`${DOMAIN}`)
    # traefik.http.middlewares.auth.basicauth.users: ${AUTH}

  whoami:
    image: 'traefik/whoami'
    container_name: 'simple-service'
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.rule: Host(`whoami.localhost`)
      traefik.http.routers.whoami.entrypoints: web
      # traefik.http.routers.whoami.tls.certresolver: default
