# [global]

[log]
  level = "DEBUG"

[accesslog]
  bufferingSize = 0
  [accessLog.filters]
    statusCodes = ["300-302", "400-410"]
    minDuration = "0s"

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.web.http]
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"


  [entryPoints.websecure]
    address = ":443"

[http.routers]
  [http.routers.router0]
    rule = "Host('srv1.mihanoos.com')"

[http.middlewares]
  [http.middlewares.test-retry.retry]
    attempts = 4
    initialInterval = "100ms"

[providers]
  providersThrottleDuration = "2s"
  [providers.docker]
    watch = true
    endpoint = "unix:///var/run/docker.sock"
    network = "alwatr-public-network"
    swarmModeRefreshSeconds = "15s"
    httpClientTimeout = "0s"

[api]
  insecure = true
  dashboard = true

[certificatesResolvers]
  [certificatesResolvers.default]
    [certificatesResolvers.default.acme]
      email = "alimihandoost@gmail.com"
      storage = "acme.json"
      certificatesDuration = 0
      [certificatesResolvers.default.acme.httpChallenge]
        entryPoint = "http"
