networks:
  internal:
  alwatr-public-network:
    name: alwatr-public-network
    external: true

services:
  pwa:
    image: ghcr.io/alimd/keep-pwa:${PWA_VERSION}

    cpu_count: 1
    cpu_shares: 1024
    mem_limit: 256m

    restart: unless-stopped

    networks:
      alwatr-public-network:

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

    environment:
      - NGINX_ACCESS_LOG=${PWA_ACCESS_LOG:-off}

    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.rule: Host:${DOMAIN}; PathPrefix:/
      traefik.frontend.entryPoints: http, https
      traefik.frontend.redirect.entryPoint: https

